name: Trigger auto deployment for sb-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/sb-container-app-AutoDeployTrigger-4660d070-1909-42c3-b9af-e59967c0cfcd.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SBCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SBCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SBCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: saifhub.azurecr.io
          registryUsername: ${{ secrets.SBCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SBCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: sb-container-app
          resourceGroup: container-app-rg
          imageToBuild: saifhub.azurecr.io/sb-container-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


